import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ChevronDown, ChevronUp, FileText, Banknote } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useStaffRecord } from "@/hooks/useRole";
import { supabase } from "@/lib/supabase";
import { cn, formatCurrency } from "@/lib/utils";
import StaffLayout from "@/components/staff/StaffLayout";
import { useSettings } from "@/hooks/useSettings";

interface Payslip {
  id: string;
  period_start: string;
  period_end: string;
  shifts_count: number;
  gross_hours: number;
  gross_pay: number;
  tax_code: string;
  paye_tax: number;
  ni_employee: number;
  ni_employer: number;
  net_pay: number;
  notes: string | null;
  status: "draft" | "finalised";
  generated_at: string;
}

function formatPeriod(start: string, end: string) {
  const s = new Date(start + "T00:00:00").toLocaleDateString("en-GB", { day: "numeric", month: "short" });
  const e = new Date(end   + "T00:00:00").toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  return `${s} – ${e}`;
}

function Row({ label, value, bold, green }: { label: string; value: string; bold?: boolean; green?: boolean }) {
  return (
    <div className={cn("flex justify-between items-center py-1.5 text-sm", bold && "font-bold")}>
      <span className={bold ? "text-gray-900" : "text-gray-500"}>{label}</span>
      <span className={green ? "text-green-600 font-black" : bold ? "text-gray-900" : "text-gray-700"}>{value}</span>
    </div>
  );
}

export default function StaffPayslips() {
  const settings = useSettings();
  const { user, loading } = useAuth();
  const [, setLocation]   = useLocation();
  const { staff, loading: staffLoading } = useStaffRecord(user?.id);

  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [fetching, setFetching] = useState(true);
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => { if (!loading && !user) setLocation("/login"); }, [user, loading]);

  useEffect(() => {
    if (!staff?.id) return;
    supabase
      .from("payslips")
      .select("*")
      .eq("staff_id", staff.id)
      .order("period_start", { ascending: false })
      .then(({ data }) => {
        setPayslips((data as Payslip[]) ?? []);
        setFetching(false);
      });
  }, [staff?.id]);

  if (loading || staffLoading || fetching) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="w-8 h-8 border-4 border-green-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <StaffLayout title="My Payslips" subtitle="Your earnings and deductions each pay period">
      {payslips.length === 0 ? (
        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm py-20 text-center">
          <div className="w-12 h-12 bg-gray-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Banknote className="w-6 h-6 text-gray-400" />
          </div>
          <p className="text-sm font-semibold text-gray-500">No payslips yet</p>
          <p className="text-xs text-gray-400 mt-1">Payslips are generated by your admin at the end of each pay period.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {payslips.map((p) => {
            const isOpen = expanded === p.id;
            return (
              <div key={p.id} className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
                {/* Row */}
                <button
                  onClick={() => setExpanded(isOpen ? null : p.id)}
                  className="w-full flex items-center gap-4 px-5 py-4 hover:bg-gray-50 transition-colors text-left"
                >
                  <div className="w-10 h-10 bg-green-50 border border-green-100 rounded-xl flex items-center justify-center shrink-0">
                    <FileText className="w-4 h-4 text-green-600" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-bold text-gray-900">{formatPeriod(p.period_start, p.period_end)}</p>
                    <p className="text-xs text-gray-400 mt-0.5">{p.shifts_count} shift{p.shifts_count !== 1 ? "s" : ""} · {p.gross_hours.toFixed(1)} hrs</p>
                  </div>
                  <div className="text-right shrink-0 mr-2">
                    <p className="text-base font-black text-gray-900">{formatCurrency(p.net_pay)}</p>
                    <p className="text-xs text-gray-400">net pay</p>
                  </div>
                  <span className={cn(
                    "text-xs font-semibold px-2 py-0.5 rounded-full shrink-0",
                    p.status === "finalised" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"
                  )}>
                    {p.status === "finalised" ? "Finalised" : "Draft"}
                  </span>
                  {isOpen ? <ChevronUp className="w-4 h-4 text-gray-400 shrink-0" /> : <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />}
                </button>

                {/* Expanded payslip */}
                {isOpen && (
                  <div className="border-t border-gray-100 px-5 py-5">
                    {/* Header */}
                    <div className="flex items-start justify-between gap-4 mb-5 flex-wrap">
                      <div>
                        <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Payslip</p>
                        <p className="text-lg font-black text-gray-900 mt-0.5">MakeMeClean</p>
                        <p className="text-xs text-gray-400 mt-0.5">{settings.email_payroll}</p>
                      </div>
                      <div className="text-right">
                        <p className="text-xs text-gray-400">Pay period</p>
                        <p className="text-sm font-bold text-gray-900">{formatPeriod(p.period_start, p.period_end)}</p>
                        <p className="text-xs text-gray-400 mt-1">Tax code</p>
                        <p className="text-sm font-bold text-gray-900">{p.tax_code}</p>
                      </div>
                    </div>

                    {/* Employee info */}
                    <div className="bg-gray-50 rounded-xl px-4 py-3 mb-4 grid sm:grid-cols-3 gap-3 text-xs">
                      <div>
                        <p className="text-gray-400 font-semibold uppercase tracking-wide mb-0.5">Employee</p>
                        <p className="font-bold text-gray-900">{staff?.first_name} {staff?.last_name}</p>
                      </div>
                      <div>
                        <p className="text-gray-400 font-semibold uppercase tracking-wide mb-0.5">Shifts</p>
                        <p className="font-bold text-gray-900">{p.shifts_count} ({p.gross_hours.toFixed(1)} hrs)</p>
                      </div>
                      <div>
                        <p className="text-gray-400 font-semibold uppercase tracking-wide mb-0.5">Generated</p>
                        <p className="font-bold text-gray-900">{new Date(p.generated_at).toLocaleDateString("en-GB")}</p>
                      </div>
                    </div>

                    {/* Earnings */}
                    <div className="mb-1">
                      <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Earnings</p>
                      <Row label="Gross pay" value={formatCurrency(p.gross_pay)} />
                    </div>

                    <div className="h-px bg-gray-100 my-3" />

                    {/* Deductions */}
                    <div className="mb-1">
                      <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Deductions</p>
                      <Row label="PAYE Income Tax"           value={`−${formatCurrency(p.paye_tax)}`} />
                      <Row label="National Insurance (Emp.)" value={`−${formatCurrency(p.ni_employee)}`} />
                    </div>

                    <div className="h-px bg-gray-100 my-3" />

                    {/* Net */}
                    <Row label="Net Pay" value={formatCurrency(p.net_pay)} bold green />

                    <div className="h-px bg-gray-100 my-3" />

                    {/* Employer NI (informational) */}
                    <p className="text-xs text-gray-400">
                      Employer NI contribution (not deducted from your pay): {formatCurrency(p.ni_employer)}
                    </p>

                    {p.notes && (
                      <p className="text-xs text-gray-500 mt-2 italic">{p.notes}</p>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </StaffLayout>
  );
}
